[package]
name = "simple-bank-account"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "^1.0"
serde_json = "^1.0"
chrono = "0.4.23"
rusty-money = { version = "0.4.1", features = ["iso"] }
